create table products
(
    products_id int primary key,
    name        varchar(255) not null
);

create table goods
(
    goods_id        int primary key,
    product_id      int references Products (products_id) not null,
    price           int check ( price > 0 ) not null,
    expiration_date date not null
);

create table customers
(
    customers_id int primary key,
    last_name    varchar(255) not null,
    first_name   varchar(255) not null,
    patronymic   varchar(255),
    age          int check ( age > 0 ) not null
);

create table purchases
(
    purchases_id int primary key generated by default as identity,
    good_id       int references Goods (goods_id) not null,
    customer_id   int references Customers (customers_id) not null,
    purchase_date date not null
);
